views:
  v1/pods:
    columns:
      - NAMESPACE
      - NAME
      - 'OWNERKIND:.metadata.ownerReferences[0].kind'
      - PF
      - READY
      - STATUS
      - RESTARTS
      - IP
      - NODE
      - AGE
      - ROLE|H
      - CPU|H
      - '%CPU/R|H'
      - '%CPU/L|H'
      - MEM|H
      - '%MEM/R|H'
      - '%MEM/L|H'
  karpenter.sh/v1/nodeclaims:
    columns:
      - TYPE
      - NAME
      - NODE
      - 'CORES:.status.capacity.cpu'
      - 'RAM:.status.capacity.memory'
      - 'MAX PODS:.status.capacity.pods'
      - NAMESPACE|H
      - NODECLASS|H
      - NODEPOOL|H
      - CAPACITY|H
  external-secrets.io/v1/externalsecrets:
    sortColumn: 'LAST SYNC:asc'
    columns:
      - NAMESPACE
      - NAME
      - STORETYPE
      - STORE
      - 'REFRESH INTERVAL'
      - 'LAST SYNC:.status.refreshTime|T'
      - STATUS
      - READY
