# ~/.zshrc

export PATH=$HOME/bin:/usr/local/bin:$PATH
export LANG=en_US.UTF-8

if [[ -z "$XDG_CONFIG_HOME" ]]; then
  export XDG_CONFIG_HOME="${HOME}/.config"
fi

# Fix locale error in brew.
# See https://discourse.brew.sh/t/failed-to-set-locale-category-lc-numeric-to-en-ru/5092/20
export LC_ALL=en_US.UTF-8

############
# homebrew #
############

# Static equivalent of `eval "$(brew shellenv)"`, which forks ruby-ish brew on every shell
export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_REPOSITORY="/opt/homebrew"
path=(/opt/homebrew/bin /opt/homebrew/sbin $path)
fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"

#########
# cache #
#########

ZSH_CACHE_DIR="${XDG_CACHE_HOME:-${HOME}/.cache}/zsh"

# Source the output of `<cmd> <args...>`, cached until the binary's resolved
# path changes (i.e. on brew upgrade). Clear with `rm -rf $ZSH_CACHE_DIR`.
_cached_source() {
  local bin=${commands[$1]:A} cache="${ZSH_CACHE_DIR}/${(j:_:)@}.zsh" first
  [[ -z $bin ]] && return 1
  [[ -s $cache ]] && read -r first < $cache
  if [[ $first != "# $bin" ]]; then
    mkdir -p ${cache:h}
    { print -r -- "# $bin"; "$@" } >| $cache.tmp && mv -f $cache.tmp $cache
  fi
  source $cache
}

# Completions that brew doesn't ship in site-functions, generated into fpath
fpath=("${ZSH_CACHE_DIR}/completions" $fpath)
_cached_completion() {
  local bin=${commands[$1]:A} out="${ZSH_CACHE_DIR}/completions/_$1" stamp="${ZSH_CACHE_DIR}/completions/.$1"
  [[ -z $bin ]] && return 1
  if [[ ! -s $out || "$(<$stamp 2>/dev/null)" != $bin ]]; then
    mkdir -p ${out:h}
    shift
    "$@" >| $out.tmp && mv -f $out.tmp $out && print -r -- $bin >| $stamp
    rm -f ~/.zcompdump
  fi
}
_cached_completion opencode opencode --completions zsh

#################
#  zinit setup  #
#################
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

############################
# zinit plugins & snippets #
############################
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-syntax-highlighting
zinit light Aloxaf/fzf-tab

# Full compinit (security audit + dump rebuild) at most once a day; otherwise
# load the dump as-is. Run `rm ~/.zcompdump` to pick up new completions sooner.
autoload -Uz compinit
() { if (( $# )); then compinit && touch ~/.zcompdump; else compinit -C; fi } ~/.zcompdump(N.mh+24)

zinit cdreplay -q

# Configure zsh to initialize starship
_cached_source starship init zsh --print-full-init
# Configure direnv hook
_cached_source direnv hook zsh

# Shell integrations
_cached_source fzf --zsh
_cached_source atuin init zsh
_cached_source zoxide init --cmd cd zsh

###################
# Source dotfiles #
###################
# `oN` = unsorted (directory order), same order `find` used to produce
for file in ~/.dotfiles/_shell/**/.*(.oN); do
	source "$file"
done
